"""fix UserAnswer

Revision ID: 272ffd1b989b
Revises: 5245d49a53e1
Create Date: 2023-02-13 23:16:14.067341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '272ffd1b989b'
down_revision = '5245d49a53e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
