"""reworked users answers

Revision ID: 30981628819b
Revises: 40a20fcaf865
Create Date: 2023-02-13 00:51:07.465342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30981628819b'
down_revision = '40a20fcaf865'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_answers', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_answers', 'created_at')
    # ### end Alembic commands ###
