"""refactored UserAnswer with m2m

Revision ID: 556ac72e336b
Revises: 272ffd1b989b
Create Date: 2023-02-15 23:47:26.621095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '556ac72e336b'
down_revision = '272ffd1b989b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserAnswersLinkAnswers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_answer_id', sa.Integer(), nullable=True),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['user_answer_id'], ['user_answers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_UserAnswersLinkAnswers_answer_id'), 'UserAnswersLinkAnswers', ['answer_id'], unique=False)
    op.create_index(op.f('ix_UserAnswersLinkAnswers_user_answer_id'), 'UserAnswersLinkAnswers', ['user_answer_id'], unique=False)
    op.alter_column('answers', 'is_right', new_column_name='is_correct')
    op.drop_index('ix_user_answers_answer_id', table_name='user_answers')
    op.drop_constraint('user_answers_answer_id_fkey', 'user_answers', type_='foreignkey')
    op.drop_column('user_answers', 'answer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_answers', sa.Column('answer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_answers_answer_id_fkey', 'user_answers', 'answers', ['answer_id'], ['id'])
    op.create_index('ix_user_answers_answer_id', 'user_answers', ['answer_id'], unique=False)
    op.alter_column('answers', 'is_correct', new_column_name='is_right')
    op.drop_index(op.f('ix_UserAnswersLinkAnswers_user_answer_id'), table_name='UserAnswersLinkAnswers')
    op.drop_index(op.f('ix_UserAnswersLinkAnswers_answer_id'), table_name='UserAnswersLinkAnswers')
    op.drop_table('UserAnswersLinkAnswers')
    # ### end Alembic commands ###
