"""added finished_at to UserTest

Revision ID: bcc5f850fb9b
Revises: 556ac72e336b
Create Date: 2023-02-16 16:44:57.097096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcc5f850fb9b'
down_revision = '556ac72e336b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tests', sa.Column('finished_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_tests', 'finished_at')
    # ### end Alembic commands ###
